# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GraphViz-ISA-Multi
version:      0.01
version_from: lib/GraphViz/ISA/Multi.pm
installdirs:  site
requires:
    GraphViz:                      0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
